use std::sync::Mutex;

use tauri::menu::{Menu, MenuItemBuilder, Submenu};
use tauri::tray::TrayIconBuilder;
use tauri::Manager;
use tauri_plugin_global_shortcut::ShortcutState;
use tokio::sync::watch;

mod commands;
mod hotkeys;
mod persistence;
mod state;
mod wm;

use state::AppState;

/// Sets up the application menu with platform-specific Settings item.
#[cfg(target_os = "macos")]
fn setup_app_menu(app: &tauri::App) -> tauri::Result<()> {
    let settings = MenuItemBuilder::with_id("settings", "Settings").accelerator("Cmd+,").build(app)?;

    let quit = MenuItemBuilder::with_id("quit", "Quit").accelerator("Cmd+Q").build(app)?;

    let app_submenu = Submenu::with_items(app, "App", true, &[&settings, &quit])?;

    let menu = Menu::with_items(app, &[&app_submenu])?;
    app.set_menu(menu)?;
    Ok(())
}

#[cfg(target_os = "windows")]
fn setup_app_menu(app: &tauri::App) -> tauri::Result<()> {
    let settings = MenuItemBuilder::with_id("settings", "Settings").accelerator("Ctrl+,").build(app)?;

    let quit = MenuItemBuilder::with_id("quit", "Quit").accelerator("Ctrl+Q").build(app)?;

    let file_submenu = Submenu::with_items(app, "File", true, &[&settings, &quit])?;

    let menu = Menu::with_items(app, &[&file_submenu])?;
    app.set_menu(menu)?;
    Ok(())
}

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
fn setup_app_menu(_app: &tauri::App) -> tauri::Result<()> {
    Ok(())
}

/// Sets up the system tray icon with menu.
fn setup_tray(app: &tauri::App) -> tauri::Result<()> {
    let open = MenuItemBuilder::with_id("open-main", "Open Context Manager").build(app)?;
    let quit = MenuItemBuilder::with_id("quit", "Quit").build(app)?;

    let menu = Menu::with_items(app, &[&open, &quit])?;

    let app_handle = app.handle().clone();
    let mut builder =
        TrayIconBuilder::with_id("main-tray").menu(&menu).on_menu_event(move |_app, event| match event.id().as_ref() {
            "open-main" => {
                let app = app_handle.clone();
                tauri::async_runtime::spawn(async move {
                    commands::open_main_window(app);
                });
            },
            "quit" => {
                app_handle.exit(0);
            },
            _ => {},
        });

    // A tray icon with no image renders as an invisible menu-bar slot, so give
    // it the app's bundled default icon.
    if let Some(icon) = app.default_window_icon() {
        builder = builder.icon(icon.clone());
    }

    let _tray = builder.build(app)?;

    Ok(())
}

/// Builds and runs the Tauri application; never returns under normal operation.
///
/// Initialises all plugins and application state in order:
/// 1. Loads persisted `AppData` from disk (or defaults).
/// 2. Spawns the debounced persistence saver task.
/// 3. Registers global hotkeys.
/// 4. Creates the system tray / menu bar icon.
/// 5. Registers `AppState` with Tauri's managed state.
/// 6. Performs an initial window sync and starts the background poll.
///
/// # Preconditions/Assumptions
/// - A valid Tauri context must exist (generated by `tauri::generate_context!()`
///   at compile time from `tauri.conf.json`).
/// - The global-shortcut plugin is added before `setup` runs; any plugin
///   ordering issue will surface as a runtime panic.
///
/// # Invariants
/// - Panics with a descriptive message if the Tauri event loop cannot start.
/// - The `AppState` mutex must never be held across `.await` points anywhere
///   in the application to avoid deadlocking the async runtime.
pub fn run() {
    tauri::Builder::default()
        .plugin(
            tauri_plugin_global_shortcut::Builder::new()
                .with_handler(|app, shortcut, event| {
                    if event.state() == ShortcutState::Pressed {
                        commands::handle_shortcut(app, shortcut);
                    }
                })
                .build(),
        )
        .on_window_event(|window, event| {
            // Keep the app alive as a tray/menu-bar app: hide the main window
            // on close instead of destroying it, so it can always be reopened
            // via the tray's "Open Context Manager" item. Destroying it would
            // leave `open_main_window` unable to find the window.
            if window.label() == "main" {
                if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                    api.prevent_close();
                    let _ = window.hide();
                }
            }
        })
        .setup(|app| {
            let app_data = persistence::load(app.handle());
            let (save_tx, save_rx) = watch::channel(app_data.clone());
            persistence::spawn_saver(app.handle().clone(), save_rx);

            app.manage(AppState { data: Mutex::new(app_data), save_tx });

            // Register the global Context shortcuts (<meta>+0..9, <meta>+H).
            // Without this the plugin handler below is never invoked.
            if let Err(e) = hotkeys::register_all(app.handle()) {
                eprintln!("failed to register global shortcuts: {e}");
            }

            wm::update_windows(app.handle());
            wm::start_poll(app.handle().clone());

            // Set up application menu with platform-specific Settings item
            setup_app_menu(app)?;

            // Set up system tray icon
            setup_tray(app)?;

            // Handle menu events for Settings
            let app_handle = app.handle().clone();
            app.on_menu_event(move |_app, event| {
                if event.id().as_ref() == "settings" {
                    let app = app_handle.clone();
                    tauri::async_runtime::spawn(async move {
                        let _ = commands::open_settings(app);
                    });
                }
            });

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::get_app_data,
            commands::create_context,
            commands::rename_context,
            commands::delete_context,
            commands::assign_shortcut,
            commands::reorder_contexts,
            commands::add_window_to_context,
            commands::remove_window_from_context,
            commands::show_context,
            commands::hide_context,
            commands::hide_all,
            commands::open_main_window,
            commands::get_settings,
            commands::update_settings,
            commands::open_settings,
            #[cfg(debug_assertions)]
            commands::open_devtools,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
