use std::sync::Mutex;

use tauri::menu::{Menu, MenuItemBuilder, Submenu};
use tauri::tray::TrayIconBuilder;
use tauri::Manager;
use tauri_plugin_global_shortcut::ShortcutState;
use tokio::sync::watch;

mod commands;
mod hotkeys;
mod persistence;
mod state;
mod wm;

use state::AppState;

/// Sets up the application menu with a Settings item, under the
/// platform-conventional submenu ("App" with Cmd accelerators on macOS,
/// "File" with Ctrl accelerators on Windows). No-op on other platforms.
fn setup_app_menu(app: &tauri::App) -> tauri::Result<()> {
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        let _ = app;
        Ok(())
    }
    #[cfg(any(target_os = "macos", target_os = "windows"))]
    {
        #[cfg(target_os = "macos")]
        const SUBMENU_TITLE: &str = "App";
        #[cfg(target_os = "macos")]
        const MODIFIER: &str = "Cmd";
        #[cfg(target_os = "windows")]
        const SUBMENU_TITLE: &str = "File";
        #[cfg(target_os = "windows")]
        const MODIFIER: &str = "Ctrl";

        let settings =
            MenuItemBuilder::with_id("settings", "Settings").accelerator(format!("{MODIFIER}+,")).build(app)?;
        let quit = MenuItemBuilder::with_id("quit", "Quit").accelerator(format!("{MODIFIER}+Q")).build(app)?;
        let submenu = Submenu::with_items(app, SUBMENU_TITLE, true, &[&settings, &quit])?;
        let menu = Menu::with_items(app, &[&submenu])?;
        app.set_menu(menu)?;
        Ok(())
    }
}

/// Sets up the system tray icon with menu.
fn setup_tray(app: &tauri::App) -> tauri::Result<()> {
    let open = MenuItemBuilder::with_id("open-main", "Open Context Manager").build(app)?;
    let quit = MenuItemBuilder::with_id("quit", "Quit").build(app)?;

    let menu = Menu::with_items(app, &[&open, &quit])?;

    let app_handle = app.handle().clone();
    let mut builder =
        TrayIconBuilder::with_id("main-tray").menu(&menu).on_menu_event(move |_app, event| match event.id().as_ref() {
            "open-main" => commands::open_main_window(&app_handle),
            "quit" => app_handle.exit(0),
            _ => {},
        });

    // A tray icon with no image renders as an invisible menu-bar slot, so give
    // it the app's bundled default icon.
    if let Some(icon) = app.default_window_icon() {
        builder = builder.icon(icon.clone());
    }

    let _tray = builder.build(app)?;

    Ok(())
}

/// Builds and runs the Tauri application; never returns under normal operation.
///
/// Initialises all plugins and application state in order:
/// 1. Loads persisted `AppData` from disk (or defaults).
/// 2. Spawns the debounced persistence saver task.
/// 3. Registers global hotkeys.
/// 4. Creates the system tray / menu bar icon.
/// 5. Registers `AppState` with Tauri's managed state.
/// 6. Performs an initial window sync and starts the background poll.
///
/// # Preconditions/Assumptions
/// - A valid Tauri context must exist (generated by `tauri::generate_context!()`
///   at compile time from `tauri.conf.json`).
/// - The global-shortcut plugin is added before `setup` runs; any plugin
///   ordering issue will surface as a runtime panic.
///
/// # Invariants
/// - Panics with a descriptive message if the Tauri event loop cannot start.
/// - The `AppState` mutex must never be held across `.await` points anywhere
///   in the application to avoid deadlocking the async runtime.
pub fn run() {
    tauri::Builder::default()
        .plugin(
            tauri_plugin_global_shortcut::Builder::new()
                .with_handler(|app, shortcut, event| {
                    if event.state() == ShortcutState::Pressed {
                        commands::handle_shortcut(app, shortcut);
                    }
                })
                .build(),
        )
        .on_window_event(|window, event| {
            // Keep the app alive as a tray/menu-bar app: hide the main window
            // on close instead of destroying it, so it can always be reopened
            // via the tray's "Open Context Manager" item. Destroying it would
            // leave `open_main_window` unable to find the window.
            if window.label() == "main" {
                if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                    api.prevent_close();
                    let _ = window.hide();
                }
            }
        })
        .setup(|app| {
            let app_data = persistence::load(app.handle());
            let (save_tx, save_rx) = watch::channel(app_data.clone());
            persistence::spawn_saver(app.handle().clone(), save_rx);

            app.manage(AppState { data: Mutex::new(app_data), save_tx });

            // Register the global Context shortcuts (<meta>+0..9, <meta>+H).
            // Without this the plugin handler below is never invoked.
            if let Err(e) = hotkeys::register_all(app.handle()) {
                eprintln!("failed to register global shortcuts: {e}");
            }

            wm::update_windows(app.handle());
            wm::start_poll(app.handle().clone());

            // Set up application menu with platform-specific Settings item
            setup_app_menu(app)?;

            // Set up system tray icon
            setup_tray(app)?;

            // Handle menu events for Settings
            let app_handle = app.handle().clone();
            app.on_menu_event(move |_app, event| {
                if event.id().as_ref() == "settings" {
                    let _ = commands::open_settings(&app_handle);
                }
            });

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::context::get_app_data,
            commands::context::create_context,
            commands::context::rename_context,
            commands::context::delete_context,
            commands::context::assign_shortcut,
            commands::context::reorder_contexts,
            commands::membership::add_window_to_context,
            commands::membership::remove_window_from_context,
            commands::visibility::show_context,
            commands::visibility::hide_context,
            commands::settings::update_settings,
            #[cfg(debug_assertions)]
            commands::settings::open_devtools,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
